#### Linear_Regression_Practical_Implementation_Part2

In [1]:
# fetching the datset 
from sklearn.datasets import fetch_california_housing 

In [4]:
dataset = fetch_california_housing()

In [5]:
dataset

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [6]:
print(dataset.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [8]:
# getting actual data
dataset.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [9]:
# getting targeted values 
print(dataset.target)

[4.526 3.585 3.521 ... 0.923 0.847 0.894]


In [10]:
# getting the features names from the dataset
print(dataset.feature_names)

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']


In [17]:
# creating the dataframe 
import pandas as pd 
df = pd.DataFrame(dataset.data , columns = dataset.feature_names)

In [18]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [19]:
# creating the target column in dataset 
df['price'] = dataset.target

In [20]:
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  price  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [21]:
# checking the null values 
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
price         0
dtype: int64

In [22]:
# Dividing the dataset into independent and dependent variables 
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [23]:
# Independent features 
X

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [24]:
# dependent features 
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: price, Length: 20640, dtype: float64

In [25]:
# Dividing the data into two types
# 1 . test data
# 2 . training data


from sklearn.model_selection import train_test_split


# It select data randmonly
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.33, random_state=36)

# random_state=36 --> when we change this value the train data also changes

In [ ]:
# X_train --> This are all have the independent features
# X_train and y_train are mainly used for the training data
# X_test and Y_test are mainly used for the test data

In [27]:
# Independent features to train the model 
X_train 

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
6556    9.5320      50.0  7.114428   0.925373       620.0  3.084577     34.19   
8399    2.8438      32.0  3.851986   1.032491      1053.0  3.801444     33.95   
17929   3.9250      35.0  5.056680   0.939271       556.0  2.251012     37.35   
19277   2.1864      29.0  4.031627   1.040663      1880.0  2.831325     38.43   
11910   3.8640      24.0  5.444714   1.094775      2398.0  2.913730     33.96   
...        ...       ...       ...        ...         ...       ...       ...   
5769    2.8342      35.0  3.923077   1.067155      2401.0  2.931624     34.16   
986    10.3203      43.0  5.428571   0.952381        83.0  1.976190     37.72   
7329    2.9844      36.0  3.582857   1.011429       834.0  4.765714     33.98   
19368   3.9336      18.0  6.188406   1.207729      1128.0  2.724638     38.38   
610     4.8036      20.0  5.370000   1.021250      1732.0  2.165000     37.69   

       Longitude  
6556     -118.11  
8399     -118.37  
17929    -121.97  
19277    -122.73  
11910    -117.41  
...          ...  
5769     -118.30  
986      -121.85  
7329     -118.17  
19368    -122.93  
610      -122.09  

[13828 rows x 8 columns]

In [28]:
# Dependent features for traning the model 
y_train

6556     4.833
8399     1.817
17929    2.871
19277    1.432
11910    1.234
         ...  
5769     2.568
986      4.000
7329     1.636
19368    2.625
610      1.883
Name: price, Length: 13828, dtype: float64

In [29]:
# Independent features to test the accuracy of the model
X_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
13210   4.0096       5.0  5.061294   1.017026      2028.0  2.301930     34.04   
12777   1.8611      42.0  4.751381   1.055249      1069.0  2.953039     38.64   
5288    4.1750      27.0  4.574844   1.073805      1725.0  1.793139     34.05   
5632    2.4500      41.0  3.536585   1.032520      1384.0  3.750678     33.75   
17603   4.1406      44.0  5.289817   1.033943       908.0  2.370757     37.29   
...        ...       ...       ...        ...         ...       ...       ...   
17366   3.6815      43.0  6.516129   1.109677       692.0  2.232258     34.95   
6862    3.3906      27.0  5.074324   1.044402      3496.0  3.374517     34.06   
5252   11.1978      32.0  7.270344   1.031646      2768.0  2.502712     34.10   
4039    8.7172      32.0  7.693431   1.127737       769.0  2.806569     34.16   
6261    3.1591      35.0  5.382075   1.000000       924.0  4.358491     34.04   

       Longitude  
13210    -117.69  
12777    -121.42  
5288     -118.47  
5632     -118.28  
17603    -121.88  
...          ...  
17366    -120.43  
6862     -118.14  
5252     -118.47  
4039     -118.48  
6261     -117.96  

[6812 rows x 8 columns]

In [30]:
# Dependent features to test the accuracy and performance of the model 
y_test

13210    1.82600
12777    0.60500
5288     5.00001
5632     1.86800
17603    2.74100
          ...   
17366    1.81800
6862     2.37200
5252     5.00001
4039     5.00001
6261     1.48300
Name: price, Length: 6812, dtype: float64

In [ ]:
# for independent values we always use the highercase letter
# for dependent values we always use the lowercase letter

In [32]:
X.shape

(20640, 8)

In [33]:
X_train.shape , X_test.shape
              # test_size=0.33

((13828, 8), (6812, 8))

In [35]:
# for standardization 
from sklearn.preprocessing import StandardScaler 
# creating the object of the StandardScaler 

scaler = StandardScaler()

In [ ]:
# Note : We only perform fit_transform on the X_train data.
# and on the X_test data we directly perform transform.

In [ ]:
# when we perform the fit_transform on the Training data it 
# convert the data in the form which if we compute the value of
# mean and std_dev of the data it will in this form mean = 0 and , std_dev = 1 

In [36]:
# This basically compute the mean and std_dev for training data 
scaler.fit(X_train)

StandardScaler()

In [37]:
# This basically applying Z-score formula on the every feature 
# in the training dataset


# The entire value are equal to
# mean = 0 , and stdDev = 1
scaler.transform(X_train)

array([[ 2.94615603,  1.69257444,  0.65840852, ...,  0.00631568,
        -0.67676958,  0.7291751 ],
       [-0.53712836,  0.26178584, -0.61551141, ...,  0.10882511,
        -0.78878315,  0.59982719],
       [ 0.02597188,  0.50025061, -0.14510172, ..., -0.11288116,
         0.79807576, -1.19114398],
       ...,
       [-0.46390242,  0.57973886, -0.72060079, ...,  0.24671234,
        -0.77478146,  0.69932558],
       [ 0.03045085, -0.85104973,  0.29681501, ..., -0.04515438,
         1.27880067, -1.66873629],
       [ 0.48355594, -0.69207322, -0.02275645, ..., -0.12518059,
         0.95676166, -1.25084302]])

In [38]:
# we can aslo do this above steps in one single command
# as below

X_train = scaler.fit_transform(X_train)

In [39]:
# performing the transform function on the test data
X_test = scaler.transform(X_test)

In [40]:
X_train

array([[ 2.94615603,  1.69257444,  0.65840852, ...,  0.00631568,
        -0.67676958,  0.7291751 ],
       [-0.53712836,  0.26178584, -0.61551141, ...,  0.10882511,
        -0.78878315,  0.59982719],
       [ 0.02597188,  0.50025061, -0.14510172, ..., -0.11288116,
         0.79807576, -1.19114398],
       ...,
       [-0.46390242,  0.57973886, -0.72060079, ...,  0.24671234,
        -0.77478146,  0.69932558],
       [ 0.03045085, -0.85104973,  0.29681501, ..., -0.04515438,
         1.27880067, -1.66873629],
       [ 0.48355594, -0.69207322, -0.02275645, ..., -0.12518059,
         0.95676166, -1.25084302]])

In [41]:
X_test

array([[ 0.07003245, -1.88439705, -0.14330011, ..., -0.10560014,
        -0.74677806,  0.93812174],
       [-1.04892878,  1.0566684 , -0.26431499, ..., -0.01249385,
         1.40014871, -0.91752338],
       [ 0.15617449, -0.13565543, -0.33324929, ..., -0.17835535,
        -0.74211083,  0.55007799],
       ...,
       [ 3.81372206,  0.26178584,  0.71929056, ..., -0.0768889 ,
        -0.71877467,  0.55007799],
       [ 2.52179968,  0.26178584,  0.88449779, ..., -0.03343845,
        -0.69077128,  0.54510307],
       [-0.37291683,  0.50025061, -0.01804122, ...,  0.18848079,
        -0.74677806,  0.8037989 ]])

In [42]:
# sklearn is the open source libarary which has all the 
# regression , classification and clusterrig algorithms 
from sklearn.linear_model import LinearRegression

regression = LinearRegression()

In [43]:
# We need to train the data and also we need to find the value
# of the coefficient so we use this

# To fit and train the model
regression.fit(X_train , y_train)

LinearRegression()

In [44]:
# To get the coefficients
regression.coef_

# Whenever we see the - minus sign mean it decreasing the price
# Whenever we see the + plus sign mean it increasing the price

array([ 0.83700024,  0.12271899, -0.26347102,  0.30713139, -0.0081633 ,
       -0.02764702, -0.90609856, -0.87576409])

In [45]:
regression.intercept_


2.0708259184263804

In [46]:
# Let's get the prediction data
y_pred=regression.predict(X_test)

In [ ]:
# Steps :
# 1. Divide the datset into  independent and dependent dataset
# 2. Divide the dataset into the train and test dataset
# 3. Feature SCalling --> standardization
# 4. Model Training
# 5. Model Fit
# 6. Coefficient And Intercept
# 7. Prediction
# 8. MSE MAE SMSE

In [47]:
y_pred

array([1.74054339, 0.90455512, 2.45240228, ..., 5.22766823, 4.15452378,
       1.73613111])

In [51]:
from sklearn.metrics import mean_squared_error,mean_absolute_error
import numpy as np

In [52]:
mse = mean_squared_error(y_test , y_pred)
print(f"Mean squred error {mse}")
mae = mean_absolute_error(y_test , y_pred)
print(f"mean absolute error {mae}")
print(f"Root mean squared error {np.sqrt(mse)}")

Mean squred error 0.5335029155157139
mean absolute error 0.540898948179417
Root mean squared error 0.730412839095613


In [56]:
# To check the accuracy of the model
# we use r2 matrix and adjusted r2 matrix

# checking the model accuracy with the r2 matrix
from sklearn.metrics import r2_score
score = r2_score(y_test , y_pred)

# 58 % accuracy

In [57]:
# 58 % accuracy
score

0.5875394343499214

In [58]:
# Calulating adusted r2 matrix
1 - (1-score)*(len(y)-1)/(len(y)-X.shape[1]-1)

0.5873794961731389

In [59]:
# Here above we have got the accuracy for the regression model 

In [60]:
# Now let's see the ridge regression model 

from sklearn.linear_model import Ridge
ridge=Ridge(alpha=20.0)
ridge.fit(X_train,y_train)

Ridge(alpha=20.0)

In [61]:
# Doing the prediction using ridge regression 
y_pred=ridge.predict(X_test)

In [62]:
# Here we are passing all the predicted values with respect to 
# the ridge regression 

mse = mean_squared_error(y_test , y_pred)
print(f"Mean squred error {mse}")
mae = mean_absolute_error(y_test , y_pred)
print(f"mean absolute error {mae}")
print(f"Root mean squared error {np.sqrt(mse)}")

Mean squred error 0.5335706984910806
mean absolute error 0.5408065397594832
Root mean squared error 0.7304592380763493


In [63]:
# lasso regression
from sklearn.linear_model import Lasso

lasso=Lasso(alpha=20.0)
lasso.fit(X_train,y_train)

Lasso(alpha=20.0)

In [64]:
# making perdiction using lasso regression 

y_pred=lasso.predict(X_test)
print(f"Mean squred error {mse}")
mae = mean_absolute_error(y_test , y_pred)
print(f"mean absolute error {mae}")
print(f"Root mean squared error {np.sqrt(mse)}")

Mean squred error 0.5335706984910806
mean absolute error 0.9000629779192262
Root mean squared error 0.7304592380763493


In [65]:
# let's try with the elastic net 

from sklearn.linear_model import ElasticNet

elasticnet=ElasticNet(alpha=20.0)
elasticnet.fit(X_train,y_train)

ElasticNet(alpha=20.0)

In [66]:
# making the prediction using elastic net 
y_pred=elasticnet.predict(X_test)

mse=mean_squared_error(y_test,y_pred)
print(mse)
mae=mean_absolute_error(y_test,y_pred)
print(mae)
print(np.sqrt(mse))

1.2935112672240048
0.9000629779192262
1.1373263679454568


In [67]:
df_copy = df.copy()

In [68]:
df_copy.corr()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
MedInc      1.000000 -0.119034  0.326895  -0.062040    0.004834  0.018766   
HouseAge   -0.119034  1.000000 -0.153277  -0.077747   -0.296244  0.013191   
AveRooms    0.326895 -0.153277  1.000000   0.847621   -0.072213 -0.004852   
AveBedrms  -0.062040 -0.077747  0.847621   1.000000   -0.066197 -0.006181   
Population  0.004834 -0.296244 -0.072213  -0.066197    1.000000  0.069863   
AveOccup    0.018766  0.013191 -0.004852  -0.006181    0.069863  1.000000   
Latitude   -0.079809  0.011173  0.106389   0.069721   -0.108785  0.002366   
Longitude  -0.015176 -0.108197 -0.027540   0.013344    0.099773  0.002476   
price       0.688075  0.105623  0.151948  -0.046701   -0.024650 -0.023737   

            Latitude  Longitude     price  
MedInc     -0.079809  -0.015176  0.688075  
HouseAge    0.011173  -0.108197  0.105623  
AveRooms    0.106389  -0.027540  0.151948  
AveBedrms   0.069721   0.013344 -0.046701  
Population -0.108785   0.099773 -0.024650  
AveOccup    0.002366   0.002476 -0.023737  
Latitude    1.000000  -0.924664 -0.144160  
Longitude  -0.924664   1.000000 -0.045967  
price      -0.144160  -0.045967  1.000000